/**
 * Markdown Export Adapter
 */
module.exports = {
  mimeType: 'text/markdown',
  fileExtension: 'md',

  /**
   * Export notes or research summaries as Markdown
   * @param {Object} data - { title, content, papers, summary }
   * @returns {string} Markdown text string
   */
  exportData: (data) => {
    const title = data.title || 'Research Export';
    const dateStr = new Date().toLocaleDateString();

    let output = `# ${title}\n`;
    output += `*Generated by Research Nexus on ${dateStr}*\n\n`;

    if (data.content) {
      output += `## Note Contents\n\n${data.content}\n\n`;
    }

    if (data.summary) {
      output += `## Research Paper Summary\n\n`;
      output += `### Abstract\n${data.abstract || 'No abstract available.'}\n\n`;
      
      const s = data.summary;
      if (s.keyPoints && s.keyPoints.length > 0) {
        output += `### Key Takeaways\n`;
        s.keyPoints.forEach((p) => {
          output += `- ${p}\n`;
        });
        output += `\n`;
      }

      if (s.methodology) output += `### Methodology\n${s.methodology}\n\n`;
      if (s.results) output += `### Results & Outperformance\n${s.results}\n\n`;
      if (s.limitations) output += `### Identified Limitations\n${s.limitations}\n\n`;
      if (s.futureWork) output += `### Future Directives\n${s.futureWork}\n\n`;
      
      if (s.keywords && s.keywords.length > 0) {
        output += `**Keywords**: ${s.keywords.join(', ')}\n\n`;
      }
    }

    if (data.citations) {
      output += `## Bibliographic Citations\n\n`;
      if (data.citations.apa) output += `- **APA**: ${data.citations.apa}\n`;
      if (data.citations.mla) output += `- **MLA**: ${data.citations.mla}\n`;
      if (data.citations.ieee) output += `- **IEEE**: ${data.citations.ieee}\n`;
    }

    return output;
  },
};
